-- The practice log.
--
-- One row per sitting. Append-only in practice: a sitting is a thing that
-- happened, so there is nothing to update and no conflict to resolve. That is
-- why this syncs more simply than `preferences` does — the merge is a union,
-- not a last-write-wins rule someone has to get right.
--
-- The id is generated by the CLIENT, not here. That is what makes the sync
-- idempotent: pushing the same sitting twice collides on the primary key and
-- does nothing, rather than quietly doubling somebody's streak. A default is
-- provided anyway so a row inserted by hand still works.

create table if not exists public.sittings (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  started_at  timestamptz not null,

  -- Minutes actually sat, not minutes intended. Someone who set an hour and
  -- stopped at twenty sat for twenty.
  minutes     int not null check (minutes between 1 and 600),

  -- Whether it ran to the bell. Ending early still counts as practice; this
  -- only records which kind it was.
  completed   boolean not null default true,

  created_at  timestamptz not null default now()
);

-- Every query is "this user's sittings, newest first".
create index if not exists sittings_user_started_idx
  on public.sittings (user_id, started_at desc);

comment on table public.sittings is
  'One row per sitting. Client-generated ids make the sync idempotent.';

-- ---------------------------------------------------------------------------
-- Row Level Security
--
-- Same shape as `preferences`, and for the same reason: `using` governs what
-- you can see and delete, `with check` governs what you can write. Without the
-- second, a user could insert rows into somebody else's history.
--
-- This is more sensitive than preferences. A preference reveals that you like
-- a gong; this table reveals when you were awake, how often, and for how long.
-- ---------------------------------------------------------------------------

alter table public.sittings enable row level security;

drop policy if exists "own sittings" on public.sittings;
create policy "own sittings" on public.sittings
  for all
  using      (auth.uid() = user_id)
  with check (auth.uid() = user_id);
